// <auto-generated />
namespace Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updatedimagetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedimagetable));
        
        string IMigrationMetadata.Id
        {
            get { return "202004232354367_updated-image-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
